#列表 insert append pop del
jiabin = ['j1','j2','j3']
print(len(jiabin))
message = ('hello,'+jiabin[0]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin[1]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin[2]+' wellcome to my home'+'.')
print(message)
print(jiabin[2]+' will not go my home')
jiabin_1 = ['j1','j2','j4']
message = ('hello,'+jiabin_1[0]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin_1[1]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin_1[2]+' wellcome to my home'+'.')
print(message)
print('I make a zhuozi,and nenggou rongnagengduoren')
jiabin_1.insert(0,'j5')
jiabin_1.insert(2,'j6')
jiabin_1.append('j7')
print(jiabin_1)
message = ('hello,'+jiabin_1[0]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin_1[1]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin_1[2]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin_1[3]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin_1[4]+' wellcome to my home'+'.')
print(message)
message = ('hello,'+jiabin_1[5]+' wellcome to my home'+'.')
print(message)
print('the book is bad,I will qing two ren')
fis_j =jiabin_1.pop()
print(fis_j.title()+' I am sorry')
two_j =jiabin_1.pop()
print(two_j.title()+' I am sorry')
thr_j =jiabin_1.pop()
print(thr_j.title()+' I am sorry')
fou_j =jiabin_1.pop()
print(fou_j.title()+' I am sorry')
print(jiabin_1)
message = ('hello '+jiabin_1[0]+' nihaizaimingdan')
print(message)
message = ('hello '+jiabin_1[1]+' nihaizaimingdan')
print(message)
del jiabin_1[1]
del jiabin_1[0]
print(jiabin_1)