where = ["beijing",'lasa','xizang','xibei','dongbei']
print(where)
print(sorted(where))
print(where)
print(sorted(where,reverse=True))
print(where)
where.reverse()
print(where)
where.reverse()
print(where)
where.sort()
print(where)
where.sort(reverse=True)
print(where)

print('The first three items in the list are:')
print(where[:3])
print('Three items from the middle of the list are:')
print(where[1:4])
print('The last three items in the list are:')
print(where[-3:])