where = ["beijing",'lasa','xizang','xibei','dongbei']
print(where)
print(sorted(where))
print(where)
print(sorted(where,reverse=True))
print(where)
where.reverse()
print(where)
where.reverse()
print(where)
where.sort()
print(where)
where.sort(reverse=True)
print(where)

print('\nThe first three items in the list are:')
print(where[:3])
print('\nThree items from the middle of the list are:')
print(where[1:4])
print('\nThe last three items in the list are:')
print(where[-3:])