where = ["beijing",'lasa','xizang','xibei','dongbei']
print(where)
print(sorted(where))
print(where)
print(sorted(where,reverse=True))
print(where)
where.reverse()
print(where)
where.reverse()
print(where)
where.sort()
print(where)
where.sort(reverse=True)
print(where)
